name: Build CUDA

on:
  workflow_dispatch:

jobs:
  build:
    name: Build llama-server CUDA
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Build
        run: |
          cmake -S . -B build -G "Ninja" -DGGML_CUDA=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j 7
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: llama-server-cuda
          path: build/bin/Release/llama-server.exe
