name: CI (CUDA, windows)

on:
  workflow_dispatch:

concurrency:
  group: release
  queue: max

env:
  GH_TOKEN: ${{ github.token }}
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  cuda:
    name: windows-cuda (${{ matrix.cuda }}, ${{ matrix.arch }})
    runs-on: windows-2022

    permissions:
      actions: write

    strategy:
      matrix:
        include:
          - cuda: '12.4'
            arch: x64
            defines: '-DGGML_CUDA_CUB_3DOT2=ON'

    steps:
      - name: Clone
        uses: actions/checkout@v6

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.24
        with:
          key: release-windows-2022-${{ matrix.arch }}-cuda-${{ matrix.cuda }}

      - name: Install Cuda Toolkit
        uses: ./.github/actions/windows-setup-cuda
        with:
          cuda_version: ${{ matrix.cuda }}
          cuda_arch: ${{ matrix.arch }}

      - name: Install Ninja
        run: choco install ninja

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -S . -B build -G "Ninja Multi-Config" ^
            -DGGML_BACKEND_DL=ON ^
            -DGGML_NATIVE=OFF ^
            -DGGML_CPU=OFF ^
            -DGGML_CUDA=ON ^
            -DLLAMA_BUILD_BORINGSSL=ON ${{ matrix.defines }}
          set /A NINJA_JOBS=%NUMBER_OF_PROCESSORS%-1
          cmake --build build --config Release -j %NINJA_JOBS% --target llama-server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: llama-server-cuda-win-x64
          path: build/bin/Release/llama-server.exe
          retention-days: 7
